kind: Namespace
apiVersion: v1
metadata:
  name: dev
  labels:
    env: dev1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-pod
          image: mysql
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: 512Mi
              cpu: 0.2
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: dev
spec:
  selector:
    app: mysql-db
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30004